
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: s2i-java11-taskrun
spec:
  params:
    - name: TLSVERIFY
      value: "false"
    - name: MAVEN_ARGS_APPEND
      value: -Plocal
  # Use service account with git and image repo credentials
  serviceAccountName: pipeline
  taskRef:
    name: s2i-java-11
    kind: ClusterTask
  resources:
    inputs:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/lematthe/quarkus-backend
    outputs:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/quarkus-backend:latest

